name: ${project.name}
version: '${project.version}'
main: de.virtualplayground.plugin.VirtualPlugin
api-version: '1.21'
authors: [ MrMending ]
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    NBTAPI:
      load: BEFORE
      required: true